### ISSUE TITLE
Todo bullet symbol setting doesn't work?

### ISSUE THREAD

**Issue by edemaine** [fabiospampinato/vscode-markdown-todo#10]
Hey Fabio! I was just playing with again, and notice that setting "Todo bullet symbol" to `*` doesn't seem to be respected: toggling a to-do item and toggling doneness both seem to force a `-` bullet symbol (including converting an existing to-do item from `*` to `-`). Hopefully an easy fix?

I tried restarting VSCode after setting the settings as follows:

![image](https://github.com/user-attachments/assets/83e2bc26-25fd-4c3e-9916-35b0cb99b4bb)

In JSON:

```json
    "markdown.todo.symbols.bullet": "*",
```

Here's an example of the mixed bullets after modifying the first two bullets:

![image](https://github.com/user-attachments/assets/e99a682b-3143-4a90-b599-9cecc0154abe)

In addition to making this option work, it might be nice to match the existing bullet type, at least during the "toggle done" operation. But I'd be happy enough with consistent `*`s (my preferred bullet).

**Comment by edemaine** [comment]
I think I see the bug:

https://github.com/fabiospampinato/vscode-markdown-todo/blob/dd28a8144b93f87b1a45664e043d7a8c6cb66bf8/src/utils.ts#L13

Should be:

```js
 const symbolBullet = isString ( config?.symbols?.bullet ) ? config.symbols.bullet : '-'; 
```

**Comment by fabiospampinato** [comment]
Thanks for the bug report and the fix 😃

I just released v2.0.1 with the fix, it might take some minutes to show up as an available update.

**Comment by fabiospampinato** [comment]
> In addition to making this option work, it might be nice to match the existing bullet type, at least during the "toggle done" operation. But I'd be happy enough with consistent *s (my preferred bullet).

It seems sensible, I didn't think about this use case.

As of v2.0.1 a pre-existing bullet symbol should be preserved whenever possible for every command.

Arguably the extension should also infer the preferred symbol from the adjacent lines, if they contain something that looks like a list item, but for now that's unimplemented.

**Comment by edemaine** [comment]
Awesome, thanks!!
