### ISSUE TITLE
Missing command

### ISSUE THREAD

**Issue by robertmarkbram** [fabiospampinato/vscode-markdown-todo#2]
I see this when I activate your extension:

![missing command](https://user-images.githubusercontent.com/453925/56465096-71b3cb80-643a-11e9-9cb7-0b7ab00c8320.png)

Do you know what's causing this?

Rob
:)

**Comment by fabiospampinato** [comment]
> Do you know what's causing this?

My guess would be: another extension, since we don't provide that code lense.
