### ISSUE TITLE
Toggle between task and regular list item

### ISSUE THREAD

**Issue by duncanawoods** [fabiospampinato/vscode-markdown-todo#4]
Thanks for the plugin, I find it useful.

The current `toggle todo` toggles between plain text and and bullet point & todo e.g.

``` markdown
- this is a list
  - this is child
     - [ ] this is a todo

- this is a list
  - this is child
     this is a todo `toggled off - it's plain text`
```

As you can see I tend to nest todos with other comments in hierarchical bullet points. I would like to toggle between a bullet point and a todo item e.g.

``` markdown
- this is a list
  - this is child
     - [ ] this is a todo

- this is a list
  - this is child
     - this is a todo `toggled off - it's still a bullet`
```

n.b I use this in conjunction with Markdown All In One. When I edit bullet point lists, new items inherit the type of the parent and the indentation. When I rattle out some todos I often do so in named categories or child bullets for supporting info so I just need to toggle the task `[ ]` on/off but keep them as bullet points.

**Comment by fabiospampinato** [comment]
Not exactly what you asked for, but in v2 there are two new commands: "markdown.todo.decrease" and "markdown.todo.increase", which can basically go smoothly between plain line <-> list <-> unchecked todo <-> checked todo. It should be a nice way to addressing it, hopefully.

**Comment by duncanawoods** [comment]
Thank you for thinking of this. The good news is that just one backspace removes "[ ] " which I think that comes from "markdown all in one". That has met my needs nicely:

- "todo toggle": bullet -> todo
- backspace: todo -> bullet

I have tried out the new increase/decrease. Interesting but not for me I think. Backspace is nice and natural for the decrease. The "todo done" and "todo toggle" remain very valuable though so thank you!
