### ISSUE TITLE
Add ability to toggle todo for a selection of lines

### ISSUE THREAD

**Issue by thisdavej** [fabiospampinato/vscode-markdown-todo#7]
Fabio, this extension is very useful in my daily workflow - thanks for creating it!

There are times  I have created a Markdown list and I want to convert all list items to todo items to create a task list.  The `Toggle Todo` command is great, but it only converts the first line in a selection to a todo item.  It would be great if one could select a group of lines in a list and convert all of them to todo items in one shot.

**Comment by fabiospampinato** [comment]
Implemented in v2.
